//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_BondarevaKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfTriangle
    {
        public int ID { get; set; }
        public string length1 { get; set; }
        public string length2 { get; set; }
        public string length3 { get; set; }
        public string TypeTriangle { get; set; }
        public string Exception { get; set; }
    }
}
